name: budipest
description: Toilets anytime, anywhere

version: 2.2.2+22

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: 0.17.0

  flutter_svg: 0.20.0-nullsafety.3
  sliding_up_panel: 1.0.2

  google_maps_flutter: 1.2.0
  geolocator: 7.0.0-nullsafety.5

  provider: 4.3.3
  shared_preferences: 0.5.12+4
  uuid: 2.2.2

  http: 0.12.2
  url_launcher: 5.7.10

  fluster: 1.1.2
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/

    - assets/secrets.json
    - assets/light_mode.json
    - assets/dark_mode.json

    - assets/logo-white.svg

    # bottom bar icons
    - assets/icons/bottom/cat_general.svg
    - assets/icons/bottom/cat_gas_station.svg
    - assets/icons/bottom/cat_restaurant.svg
    - assets/icons/bottom/cat_shop.svg
    - assets/icons/bottom/cat_portable.svg
    - assets/icons/bottom/tag_baby_room.svg
    - assets/icons/bottom/tag_wheelchair_accessible.svg
    - assets/icons/bottom/tag_key.svg
    - assets/icons/bottom/tag_free.svg
    - assets/icons/bottom/tag_guests.svg
    - assets/icons/bottom/tag_paid.svg

    # suggest edit icons
    # - assets/icons/edit/delete.svg
    # - assets/icons/edit/nametag.svg
    # - assets/icons/edit/opening.svg
    # - assets/icons/edit/services.svg

    # map marker icons - light
    - assets/icons/pin/l_gas_station_unknown.svg
    - assets/icons/pin/l_gas_station_closed.svg
    - assets/icons/pin/l_gas_station_open.svg
    - assets/icons/pin/l_general_unknown.svg
    - assets/icons/pin/l_general_closed.svg
    - assets/icons/pin/l_general_open.svg
    - assets/icons/pin/l_portable_unknown.svg
    - assets/icons/pin/l_portable_closed.svg
    - assets/icons/pin/l_portable_open.svg
    - assets/icons/pin/l_restaurant_unknown.svg
    - assets/icons/pin/l_restaurant_closed.svg
    - assets/icons/pin/l_restaurant_open.svg
    - assets/icons/pin/l_shop_unknown.svg
    - assets/icons/pin/l_shop_closed.svg
    - assets/icons/pin/l_shop_open.svg
    - assets/icons/pin/l_gas_station_unknown.svg

    # map marker icons - dark
    # - assets/icons/pin/d_gas_station_closed.svg
    # - assets/icons/pin/d_gas_station_open.svg
    # - assets/icons/pin/d_general_unknown.svg
    # - assets/icons/pin/d_general_closed.svg
    # - assets/icons/pin/d_general_open.svg
    # - assets/icons/pin/d_portable_unknown.svg
    # - assets/icons/pin/d_portable_closed.svg
    # - assets/icons/pin/d_portable_open.svg
    # - assets/icons/pin/d_restaurant_unknown.svg
    # - assets/icons/pin/d_restaurant_closed.svg
    # - assets/icons/pin/d_restaurant_open.svg
    # - assets/icons/pin/d_shop_unknown.svg
    # - assets/icons/pin/d_shop_closed.svg
    # - assets/icons/pin/d_shop_open.svg

  fonts:
    - family: Muli
      fonts:
        - asset: fonts/Muli-Bold.ttf
          weight: 700
        - asset: fonts/Muli-Regular.ttf

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icons/icon.png"
